### PR TITLE
Refactor usage documentation

### PR DESCRIPTION
**Pull request by AdeelH**
## Overview

This PR restructures and updates the documentation in an attempt to emphasize how Raster Vision may be used as a library rather than only as a framework (#1395).

To this end, most of the previous framework-related pages have been moved to the the section, [_The Raster Vision Pipeline_](https://raster-vision--1561.org.readthedocs.build/en/1561/framework/index.html) and ~a new [_Usage_](https://raster-vision--1561.org.readthedocs.build/en/1561/usage/index.html) section has been added~ new pages, [_Usage Overview_](https://raster-vision--1561.org.readthedocs.build/en/1561/usage/overview.html) and [_Basic Concepts_](https://raster-vision--1561.org.readthedocs.build/en/1561/usage/basics.html), have been added.

Other changes:
- A table establishing the correspondence between classes and their configs has been added to [_Pipelines and Commands_](https://raster-vision--1561.org.readthedocs.build/en/1561/framework/pipelines.html) page. Also some of the descriptions of common classes on that page have been moved to the [_Basic Concepts_](https://raster-vision--1561.org.readthedocs.build/en/1561/usage/basics.html) page.
- The old Setup doc has been broken up into 3 smaller docs and turned into a ~[_Getting started_](https://raster-vision--1561.org.readthedocs.build/en/1561/setup/index.html)~ [_Setup_](https://raster-vision--1561.org.readthedocs.build/en/1561/setup/index.html) section.
- A new [_Contributing_](https://raster-vision--1561.org.readthedocs.build/en/1561/CONTRIBUTING.html) section has been added. It contains contribution instructions, release process notes, and the code of conduct.
- ~Tutorials have been moved into the Usage section~.
- Some figures now get color-inverted in dark mode. See commits or `docs/README.md` for details.

### Checklist

- ~[ ] Added `needs-backport` label if PR is bug fix that applies to previous minor release~
- [x] Ran scripts/format_code and committed any changes
- [x] Documentation updated if needed
- [x] PR has a name that won't get you publicly shamed for vagueness

### Notes

N/A

### CODE REVIEW

**Review by lewfish — CHANGES_REQUESTED** [review]
This looks really good. There are two things that need to be updated, but I'm guessing you'll do them in another PR: using the updated RV summary image from Gates, and updating the README. 

The only problem I noticed was that the edges of the graphs in the new figures you made don't show up because of the transparent background and black background of the docs. See https://raster-vision--1561.org.readthedocs.build/en/1561/usage/basics.html#reading-geospatial-data

**Comment by lewfish** [comment]
I was looking at the navigation sidebar and thinking that it's strange how "The Raster Vision Pipeline" is at the same level as "Usage". Perhaps it would make more sense to nest "The Raster Vision Pipeline" under "Usage", or better yet, move "Overview," "Basic Concepts," and "Tutorials" to the top level. This will also make the tree flatter and make more of the different sections in the docs visible at a glance without clicking on anything.

**Comment by AdeelH** [comment]
>but I'm guessing you'll do them in another PR

Yep.

>The only problem I noticed was that the edges of the graphs in the new figures you made don't show up because of the transparent background and black background of the docs. 

Good catch. I hadn't tested it in dark mode. Let me see what can be done about this.

>Or, better yet, move "Overview," "Basic Concepts," and "Tutorials" to the top level, and rename "Overview" to "Usage Overview". This will also make the tree flatter and make more of the different sections in the docs visible at a glance without clicking on anything.
>
>I also think it might be better to rename "Getting started" to "Setup" since I would kind of expect a quick start type example to be there if the section is named "Getting Started".

These are all good suggestions. Will do.

**Comment by AdeelH** [comment]
> > The only problem I noticed was that the edges of the graphs in the new figures you made don't show up because of the transparent background and black background of the docs.
> 
> Good catch. I hadn't tested it in dark mode. Let me see what can be done about this.

Figured out a trick to do this without creating new images.

**Comment by AdeelH** [comment]
You might need to hard-refresh for the changes to show up in the PR build.

**Review by lewfish — APPROVED** [review]

**Pull request merged**
