### PR TITLE
Potsdam Example

### PR DESCRIPTION
**Pull request by jamesmcclain**
## Overview

Workflow configuration for doing DeepLab-based segmentation on the Potsdam dataset.

### Checklist

- [x] Ran scripts/format_code and commited any changes
- [x] Documentation updated if needed
- [x] PR has a name that won't get you publicly shamed for vagueness
- [x] https://github.com/azavea/raster-vision/pull/366
- [x] https://github.com/azavea/raster-vision/pull/370

### CODE REVIEW

**Comment by jamesmcclain** [comment]
No boundary, don't care states:
```json
[
    {
        "recall": 0.662539520252265,
        "f1": 0.6647613414277298,
        "precision": 0.6703260280999104,
        "count_error": 317184.1630125928,
        "class_name": "car",
        "class_id": 1,
        "gt_count": 1324321
    },
    {
        "recall": 0.9959544386870036,
        "f1": 0.9958826893950703,
        "precision": 0.9958117943894249,
        "count_error": 292520.56930478965,
        "class_name": "not car",
        "class_id": 2,
        "gt_count": 106675679
    },
    {
        "recall": 0.9918660277777775,
        "f1": 0.9918224027778345,
        "precision": 0.9918206125792555,
        "count_error": 292822.9999999999,
        "class_name": "average",
        "class_id": null,
        "gt_count": 108000000
    }
]
```

**Comment by jamesmcclain** [comment]
Higher car probability in training chips:
```json
[
    {
        "class_id": 1,
        "count_error": 353731.5340616059,
        "recall": 0.6757311860190995,
        "f1": 0.6431667668843513,
        "gt_count": 1324321,
        "class_name": "car",
        "precision": 0.6181710392192299
    },
    {
        "class_id": 2,
        "count_error": 329176.90546014707,
        "recall": 0.9947598364946896,
        "f1": 0.9953640575640661,
        "gt_count": 106675679,
        "class_name": "not car",
        "precision": 0.9959705893795041
    },
    {
        "class_id": null,
        "count_error": 329477.99999999994,
        "recall": 0.9908478333333333,
        "f1": 0.9910453328586007,
        "gt_count": 108000000,
        "class_name": "average",
        "precision": 0.9913379238418393
    }
]
```

**Comment by jamesmcclain** [comment]
```json
[
    {
        "class_id": 1,
        "gt_count": 236366,
        "f1": 0.6648303041446517,
        "recall": 0.8107680461656922,
        "count_error": 193226,
        "class_name": "Car",
        "precision": 0.5634158101465296
    },
    {
        "class_id": 2,
        "gt_count": 5224016,
        "f1": 0.7865370625277049,
        "recall": 0.7808670570687379,
        "count_error": 2214190,
        "class_name": "Building",
        "precision": 0.7922900119603054
    },
    {
        "class_id": 3,
        "gt_count": 14361165,
        "f1": 0.8578921775037369,
        "recall": 0.9144056906246812,
        "count_error": 4350547,
        "class_name": "Low Vegitation",
        "precision": 0.807957537584497
    },
    {
        "class_id": 4,
        "gt_count": 2457928,
        "f1": 0.6739181040518114,
        "recall": 0.6295469191937274,
        "count_error": 1497431,
        "class_name": "Tree",
        "precision": 0.7250182147015483
    },
    {
        "class_id": 5,
        "gt_count": 6774022,
        "f1": 0.7947538361503931,
        "recall": 0.8435374139617497,
        "count_error": 2951368,
        "class_name": "Impervious",
        "precision": 0.7513042972914268
    },
    {
        "class_id": 6,
        "gt_count": 4724343,
        "f1": 0.8004741639916679,
        "recall": 0.7829956461670967,
        "count_error": 1844092,
        "class_name": "Clutter",
        "precision": 0.8187508313912991
    },
    {
        "class_id": 7,
        "gt_count": 2222160,
        "f1": null,
        "recall": 0.0,
        "count_error": 2222160,
        "class_name": "Don't Care",
        "precision": null
    },
    {
        "class_id": null,
        "gt_count": 36000000,
        "f1": 0.7613387014973763,
        "recall": 0.7878748055555554,
        "count_error": 3094857.969256417,
        "class_name": "average",
        "precision": 0.7392992699651628
    }
]
```

**Comment by jamesmcclain** [comment]
```json
[
    {
        "f1": 0.7821197445914225,
        "class_id": 1,
        "recall": 0.8984181327638843,
        "gt_count": 1324321,
        "precision": 0.6934873358536986,
        "class_name": "Car",
        "count_error": 240940.3487560795
    },
    {
        "f1": 0.9068161350611001,
        "class_id": 2,
        "recall": 0.9432931701711267,
        "gt_count": 27351432,
        "precision": 0.8743033492261657,
        "class_name": "Building",
        "count_error": 1953242.98558931
    },
    {
        "f1": 0.8304996170685279,
        "class_id": 3,
        "recall": 0.8927889205886431,
        "gt_count": 27837580,
        "precision": 0.7765731880708139,
        "class_name": "Low Vegitation",
        "count_error": 4067991.9693355532
    },
    {
        "f1": 0.8053088415972058,
        "class_id": 4,
        "recall": 0.772615005302661,
        "gt_count": 15629888,
        "precision": 0.8477427572977976,
        "class_name": "Tree",
        "count_error": 2137018.1995975915
    },
    {
        "f1": 0.8657254308636202,
        "class_id": 5,
        "recall": 0.8975641431448393,
        "gt_count": 27141209,
        "precision": 0.8361866215555784,
        "class_name": "Impervious",
        "count_error": 2620415.145902749
    },
    {
        "f1": 0.3027995349754732,
        "class_id": 6,
        "recall": 0.2945094627259128,
        "gt_count": 1191887,
        "precision": 0.32094237114495594,
        "class_name": "Clutter",
        "count_error": 652947.7394123771
    },
    {
        "f1": 0.0,
        "class_id": 7,
        "recall": 0.0,
        "gt_count": 7523683,
        "precision": 0.0,
        "class_name": "Don't Care",
        "count_error": 2530566.133932676
    },
    {
        "f1": 0.7907613117742592,
        "class_id": null,
        "recall": 0.8206590740740741,
        "gt_count": 108000000,
        "precision": 0.7664586476162002,
        "class_name": "average",
        "count_error": 2697464.2086025733
    }
]
```

**Comment by jamesmcclain** [comment]
```json
[
    {
        "recall": 0.9670062944906395,
        "count_error": 181404.87781128276,
        "precision": 0.7344445755414565,
        "class_name": "Car",
        "gt_count": 1293671,
        "class_id": 1,
        "f1": 0.8347017840939415
    },
    {
        "recall": 0.9564480515623222,
        "count_error": 1224646.235099014,
        "precision": 0.9249478059391611,
        "class_name": "Building",
        "gt_count": 26817101,
        "class_id": 2,
        "f1": 0.940177498150599
    },
    {
        "recall": 0.9188554746309848,
        "count_error": 3491073.559828708,
        "precision": 0.7920710605956798,
        "class_name": "Low Vegitation",
        "gt_count": 27294004,
        "class_id": 3,
        "f1": 0.8505720359890414
    },
    {
        "recall": 0.8083613417760063,
        "count_error": 1758295.171609188,
        "precision": 0.8748202147752941,
        "class_name": "Tree",
        "gt_count": 15350431,
        "class_id": 4,
        "f1": 0.8385276746727909
    },
    {
        "recall": 0.9252414119129685,
        "count_error": 2104017.256263363,
        "precision": 0.8555947930891796,
        "class_name": "Impervious",
        "gt_count": 26433244,
        "class_id": 5,
        "f1": 0.8890145674234331
    },
    {
        "recall": 0.4722862317083856,
        "count_error": 671305.1671493961,
        "precision": 0.35515544873032184,
        "class_name": "Clutter",
        "gt_count": 1175607,
        "class_id": 6,
        "f1": 0.4000269881191687
    },
    {
        "recall": 0.0,
        "count_error": 2469914.693314888,
        "precision": 0.0,
        "class_name": "Don't Care",
        "gt_count": 7344230,
        "class_id": 7,
        "f1": 0.0
    },
    {
        "recall": 0.8457278865399844,
        "count_error": 2174823.970075298,
        "precision": 0.7930870622278126,
        "class_name": "average",
        "gt_count": 105708288,
        "class_id": null,
        "f1": 0.8168683584154778
    }
]
```

**Comment by jamesmcclain** [comment]
```json
[
    {
        "class_id": 1,
        "precision": 0.9667752212260057,
        "count_error": 41364.53088922918,
        "f1": 0.9523274567794744,
        "class_name": "Car",
        "recall": 0.9391050738557176,
        "gt_count": 1293671
    },
    {
        "class_id": 2,
        "precision": 0.9991890788099228,
        "count_error": 39922.989101053034,
        "f1": 0.9993807658016542,
        "class_name": "~Car",
        "recall": 0.9995726812132727,
        "gt_count": 97070387
    },
    {
        "class_id": 7,
        "precision": null,
        "count_error": 0,
        "f1": null,
        "class_name": "Don't Care",
        "recall": null,
        "gt_count": 0
    },
    {
        "class_id": null,
        "precision": 0.998762776068789,
        "count_error": 39941.948066803016,
        "f1": 0.9987619269435011,
        "class_name": "average",
        "recall": 0.9987774192886594,
        "gt_count": 98364058
    }
]
```

**Comment by jamesmcclain** [comment]
# RGB 7-Class #

2_12-rgb

3_12-rgb

6_12-rgb

```json
[
    {
        "gt_count": 1324321,
        "class_name": "Car",
        "class_id": 1,
        "precision": 0.7349024715959149,
        "f1": 0.8340032833424718,
        "count_error": 184344.43014948792,
        "recall": 0.9642526245525065
    },
    {
        "gt_count": 27351432,
        "class_name": "Building",
        "class_id": 2,
        "precision": 0.914569575699137,
        "f1": 0.9338235349927888,
        "count_error": 1347092.0152333155,
        "recall": 0.9546072761382292
    },
    {
        "gt_count": 27837580,
        "class_name": "Low Vegitation",
        "class_id": 3,
        "precision": 0.7901526071965241,
        "f1": 0.8427127770837377,
        "count_error": 3800052.4343503998,
        "recall": 0.9033594874267088
    },
    {
        "gt_count": 15629888,
        "class_name": "Tree",
        "class_id": 4,
        "precision": 0.8706033448371655,
        "f1": 0.8354618423451905,
        "count_error": 1832298.7818150711,
        "recall": 0.8059982899429605
    },
    {
        "gt_count": 27141209,
        "class_name": "Impervious",
        "class_id": 5,
        "precision": 0.8503286294003015,
        "f1": 0.8845336449120802,
        "count_error": 2242872.8234221623,
        "recall": 0.9216680804454953
    },
    {
        "gt_count": 1191887,
        "class_name": "Clutter",
        "class_id": 6,
        "precision": 0.3459173543495335,
        "f1": 0.3924499778311925,
        "count_error": 698149.5172830982,
        "recall": 0.47275790406305296
    },
    {
        "gt_count": 7523683,
        "class_name": "Don't Care",
        "class_id": 7,
        "precision": 0.0,
        "f1": 0.0,
        "count_error": 2530566.133932676,
        "recall": 0.0
    },
    {
        "gt_count": 108000000,
        "class_name": "average",
        "class_id": null,
        "precision": 0.7878022682344723,
        "f1": 0.8114650639221466,
        "count_error": 2335717.481824805,
        "recall": 0.8399122314814815
    }
]
```

**Comment by jamesmcclain** [comment]
# RGB 2-Class #

2_12-car

3_12-car

6_12-car

```json
[
    {
        "precision": 0.9668333563639953,
        "class_name": "Car",
        "count_error": 42882.16229524413,
        "class_id": 1,
        "recall": 0.9377665988835033,
        "f1": 0.9516426068060169,
        "gt_count": 1324321
    },
    {
        "precision": 0.9991694605203525,
        "class_name": "~Car",
        "count_error": 41416.94328312867,
        "class_id": 2,
        "recall": 0.9995729385014096,
        "f1": 0.9993710759420378,
        "gt_count": 99151996
    },
    {
        "precision": null,
        "class_name": "Don't Care",
        "count_error": 0,
        "class_id": 7,
        "recall": null,
        "f1": null,
        "gt_count": 0
    },
    {
        "precision": 0.9987432567832824,
        "class_name": "average",
        "count_error": 41436.25549883562,
        "class_id": null,
        "recall": 0.9987583044071969,
        "f1": 0.998741994225451,
        "gt_count": 100476317
    }
]
```

**Comment by lewfish** [comment]
What do you think is causing all that junk to appear on the right and bottom border of the 7-class predictions?

**Comment by lewfish** [comment]
Despite the F1 score being a little low for cars, the predictions (including for cars) look comparable to the ones we're used to seeing. Could you clarify what the don't care class is for? Is it for ignoring boundary pixels?

**Comment by jamesmcclain** [comment]
> What do you think is causing all that junk to appear on the right and bottom border of the 7-class predictions?

The respective linear dimensions of the image are not divisible by the chip size.  That extra stuff is not counted in the scoring.

**Comment by lewfish** [comment]
> The respective linear dimensions of the image are not divisible by the chip size. That extra stuff is not counted in the scoring.

I think we need a way of dealing with that. Maybe at the end of prediction, we just crop the prediction image so it matches the dimensions of the input image.

**Comment by jamesmcclain** [comment]
> Could you clarify what the don't care class is for? Is it for ignoring boundary pixels?

That is just the name given to the class of boundary pixels.  Now that I look at it, that probably should not have been assigned to a non-zero class value.

**Comment by jamesmcclain** [comment]
```json
[
    {
        "class_name": "Car",
        "count_error": 37677.626304347665,
        "f1": 0.9569543073384768,
        "gt_count": 1324321,
        "class_id": 1,
        "precision": 0.9497922754266837,
        "recall": 0.9642526245525065
    },
    {
        "class_name": "Building",
        "count_error": 983792.2287994646,
        "f1": 0.9498276787761188,
        "gt_count": 27351432,
        "class_id": 2,
        "precision": 0.9454655821526814,
        "recall": 0.9546072761382292
    },
    {
        "class_name": "Low Vegitation",
        "count_error": 2797158.157482942,
        "f1": 0.8798424384513758,
        "gt_count": 27837580,
        "class_id": 3,
        "precision": 0.8575358250313474,
        "recall": 0.9033594874267088
    },
    {
        "class_name": "Tree",
        "count_error": 1534945.6365290654,
        "f1": 0.8594072413480189,
        "gt_count": 15629888,
        "class_id": 4,
        "precision": 0.9239407586289309,
        "recall": 0.8059982899429605
    },
    {
        "class_name": "Impervious",
        "count_error": 1401455.389019885,
        "f1": 0.9239795337960673,
        "gt_count": 27141209,
        "class_id": 5,
        "precision": 0.926331777771104,
        "recall": 0.9216680804454953
    },
    {
        "class_name": "Clutter",
        "count_error": 570692.8603340753,
        "f1": 0.4423568272439105,
        "gt_count": 1191887,
        "class_id": 6,
        "precision": 0.4305340488220003,
        "recall": 0.47275790406305296
    },
    {
        "class_name": "average",
        "count_error": 1667383.5776175396,
        "f1": 0.9034641072651011,
        "gt_count": 100476317,
        "class_id": null,
        "precision": 0.9065359398317873,
        "recall": 0.9028049963256516
    }
]
```

**Comment by jamesmcclain** [comment]
> I think we need a way of dealing with that. Maybe at the end of prediction, we just crop the prediction image so it matches the dimensions of the input image.

That can be done.  Perhaps we should wait until the large refactor PR is in, though, because that change would touch code that is under revision.

**Comment by lewfish** [comment]
> That can be done. Perhaps we should wait until the large refactor PR is in, though, because that change would touch code that is under revision.

Ok, I made a new issue: https://github.com/azavea/raster-vision/issues/397

**Pull request closed without merging**
