### PR TITLE
Windows ansible provision support

### PR DESCRIPTION
**Pull request by pomadchin**
As Windows has no native Ansible support, here is a convenient solution how to achieve provisioning  on Windows. Solution is inspired by https://github.com/ontic/ansible-windows, and uses VM to provision everything.

### CODE REVIEW

**Comment by lossyrob** [comment]
@pomadchin what's going on with this PR?

**Comment by lossyrob** [comment]
@pomadchin hey, can you explain what's up with this commit? Were you running this on windows?

**Comment by pomadchin** [comment]
Ah, sorry for that, updated the description; Yes, it allows to run and provision Vagrant on Windows.

**Comment by lewfish** [comment]
I merged a PR that contains this commit. See #86

**Pull request closed without merging**
