### PR TITLE
Add nodata handling to rasterio raster source.

### PR DESCRIPTION
**Pull request by lossyrob**
## Overview

This small change ensures that if the incoming raster has a non-zero NODATA value that  it is replaced with a 0, which the system expects.

### Notes

We haven't written unit tests for the raster source code yet, this seemed like a small enough change that could go through; debatable.

### CODE REVIEW

**Comment by lewfish** [comment]
Does this also handle nodata masks?

**Comment by lewfish** [comment]
I can take this commit and then add a test and change the predict functionality to throw out boxes over nodata.

**Comment by lewfish** [comment]
I will open another PR on this topic soon.

**Comment by lossyrob** [comment]
Superseded by #361

**Pull request closed without merging**
