### PR TITLE
Add support for nvidia-docker2 with Deep Learning Base AMI 

### LINKED ISSUE #233: Installing Nvidia drivers doesn't work
When building the AMI, the `install-nvidia-drivers.sh` fails with base AMI `'ami-9109beee` (latest deep learning ami) and Nvidia drivers 384.125. I was able to get it to run with the `--install-libglvnd` flag. But, when I start an instance with the resulting AMI, running `nvidia-smi` reports that the drivers aren't installed. At the moment, the latest base AMI has the Nvidia drivers we need, so I've commented out installing them, but in the future we may need this.

### PR DESCRIPTION
**Pull request by rbreslow**
## Overview

Add support for [nvidia-docker2](https://github.com/NVIDIA/nvidia-docker/wiki/About-version-2.0) with [Deep Learning Base AMI](https://docs.aws.amazon.com/batch/latest/userguide/batch-gpu-ami.html)

* Update driver.py AMI search regex
* Add nvidia-docker2 configuration scripts

Connects raster-foundry/prediction-api#59 and #152 
Resolves #233 

## Notes

The AMI that `driver.py` was returning is outdated, so I fixed it. You may need to update the regex again if you want to use the new Deep Learning AMI with preinstalled ML libraries. The Deep Learning Base AMI is just Amazon Linux optimized for GPU workloads with NVIDIA/CUDA drivers preinstalled.

Also, we are publishing identical AMIs in Raster Foundry that I have successfully tested with AWS Batch on `p3.2xlarge` instances. I did not investigate anything with Raster Vision deployment in #152, because that wasn't in the scope of the changes we made with raster-foundry/prediction-api#59.

nvidia-docker2 configures itself as a Docker runtime. We don't need to add volume mounts, etc anymore, everything should just work. If you have any questions, I have experience with this workflow on AWS Batch with Raster Foundry.

## Testing Instructions

First, I brought up a dev environment:

```bash
$ mkdir ~/raster_vision_data && export RASTER_VISION_DATA_DIR=~/raster_vision_data/
$ ./scripts/setup
$ vagrant ssh
```

Then, run `batch_amis.py`, and make sure it finds the latest Deep Learning Base AMI:

```bash
vagrant@raster-vision:/vagrant$ cd deployment/ && ./batch_amis.py  build-amis --aws-profile raster-vision
Creating GPU Workload AMI in us-east-1 region
Found AMI: ami-a8c5c0d7
Running Packer Command: packer build -var raster_vision_gpu_version=d643ca2 -var aws_region=us-east-1 -var aws_gpu_ami=ami-a8c5c0d7 -var branch=feature/jrb/add-p3-packer /vagrant/deployment/packer/template.js
...
```

Ensure that the `nvidia-docker2` installation was successful:

```bash
...
    raster-vision-gpu: +-----------------------------------------------------------------------------+
    raster-vision-gpu: | NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
    raster-vision-gpu: |-------------------------------+----------------------+----------------------+
    raster-vision-gpu: | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    raster-vision-gpu: | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    raster-vision-gpu: |===============================+======================+======================|
    raster-vision-gpu: |   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
    raster-vision-gpu: | N/A   39C    P0    26W / 300W |      0MiB / 16160MiB |      0%      Default |
    raster-vision-gpu: +-------------------------------+----------------------+----------------------+
...
```

Finally, ensure the AMI is built:

```bash
...
==> Builds finished. The artifacts of successful builds are:
--> raster-vision-gpu: AMIs were created:

us-east-1: ami-069ba3044e1b1f4ea
```

### CODE REVIEW

**Comment by hectcastro** [comment]
Good write-up of the details. I think that it would be a good to include the removal of the NVIDIA specific volume mounts in `job_def_gpu.json` as part of this PR too.

Also, if we can sort out the base AMI concern (ML libraries pre-installed or not), we can update the GPU Batch environment to test a workflow and possibly resolve https://github.com/azavea/raster-vision/issues/152 as well.

**Comment by lossyrob** [comment]
We won't need the pre-installed libraries, since we'll be running everything in docker containers, so looks good for the DL Base AMI.

**Comment by lewfish** [comment]
Looks good and I agree with the comments the others made. I'm curious to see how you configure the Batch environment to utilize the nvidia-docker runtime.

**Comment by rbreslow** [comment]
>I'm curious to see how you configure the Batch environment to utilize the nvidia-docker runtime.

You don't, that's the cool thing. Any container ran on our AMI will automatically utilize the runtime.

```json
{
    "containerPath": "/opt/data",
    "readOnly": false,
    "sourceVolume": "home"
}
```

Do we know what this volume mount is being used for?

**Comment by lewfish** [comment]
> Also, do we know what this volume mount is being used for?
> 
> {
>     "containerPath": "/opt/data",
>     "readOnly": false,
>     "sourceVolume": "home"
> }

The container has a limited amount of free disk space (less than that of the instance) so I mount that directory as a workaround. Maybe there's a more direct way of using all available disk space.

**Comment by rbreslow** [comment]
I destroyed the existing GPU batch environment to bring up a new queue and compute environment with `setup_aws_batch`. I was able to get a job to succeed on the new instance.

See:

* https://console.aws.amazon.com/batch/home?region=us-east-1#/job-definitions/arn:aws:batch:us-east-1:279682201306:job-definition~2Fnvidia-docker2-test:1
* https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/batch/job;stream=nvidia-docker2-test/default/ddb64eea-5576-47b6-8346-44de975feda1

> Maybe there's a more direct way of using all available disk space.

Yeah, I want to investigate. I mounted `/tmp` as well.

**Comment by rbreslow** [comment]
Worth mentioning https://azavea.slack.com/archives/C5N0EJ4NS/p1534689235000100?thread_ts=1534526740.000100&cid=C5N0EJ4NS.

We should consider setting up a volume mount for `/tmp`, once we resolve issues with `run_rv`.

**Pull request merged**
