### PR TITLE
Add ability to crop raster source extent

### PR DESCRIPTION
**Pull request by AdeelH**
## Overview

Allows different portions of the same scene image to be used in different dataset splits.
- Adds an `extent_crop` field to `RasterSourceConfig` that is passed on to the RasterSources. 
https://github.com/azavea/raster-vision/blob/1d278f855deea3a5879912d8ff82be109f5d3200/rastervision_core/rastervision/core/data/raster_source/raster_source_config.py#L23-L33
- Updates `RaterioSource` and `MultiRasterSource` to make use of `extent_crop`.
- Some minor improvements to `Box()`.
- Adds unit tests.

### Checklist

- [x] Updated `docs/changelog.rst`
- [x] Added `needs-backport` label if PR is bug fix that applies to previous minor release
- [x] Ran scripts/format_code and committed any changes
- [x] Documentation updated if needed
- [x] PR has a name that won't get you publicly shamed for vagueness

## Testing Instructions

* How to test this PR
    - See new unit tests

### CODE REVIEW

**Review by lewfish — CHANGES_REQUESTED** [review]
Thanks for the tests! It's a little confusing that the coordinate system is flipped for top vs. bottom and left vs. right. Eg. top=0.2 and bottom=0.8 refer to the same point. Being a little more explicit in the docs would be helpful.

**Comment by AdeelH** [comment]
>Thanks for the tests! It's a little confusing that the coordinate system is flipped for top vs. bottom and left vs. right. Eg. top=0.2 and bottom=0.8 refer to the same point. Being a little more explicit in the docs would be helpful.

`(top=0.2, left=0.0, bottom=0.0, right=0.0)` means skip the top 20% of the image and use the bottom 80%.
 
Untitled drawing

`(top=0.0, left=0.0, bottom=0.8, right=0.0)` means use the top 20% and skip the bottom 80% of the image.
Copy of Untitled drawing

**Comment by AdeelH** [comment]
I have updated it to use a NamedTuple and elaborated the usage a bit more in the description.

**Comment by AdeelH** [comment]
blank comment

**Comment by AdeelH** [comment]
@lewfish, it seems like `[skip ci]` has disabled CI entirely instead of for just that one commit. I don't know how to re-enable it.

**Review by lewfish — APPROVED** [review]

**Pull request merged**
