### PR TITLE
Fix CI errors in #1001

### PR DESCRIPTION
**Pull request by AdeelH**
Apparently the CI test wasn't running for previous commits in #1001 so some errors slipped into master. This fixes the flake8 errors in the CI test.

### CODE REVIEW

**Comment by AdeelH** [comment]
@lewfish can you enable the CI check for this? I don't know why it isn't running.

**Comment by lewfish** [comment]
I think you only want the last commit here. You just need to rebase off of `master`.

**Comment by lewfish** [comment]
I'm not sure why CI isn't running. I'm going to try to make a PR with that one commit and see what happens.

**Comment by lewfish** [comment]
CI is running for #1006. Maybe it's not running for this PR because it's a draft.

**Pull request closed without merging**
