### PR TITLE
Patch DeepLab to Support Custom Datasets

### PR DESCRIPTION
**Pull request by jamesmcclain**
## Overview

This patches DeepLab to allow custom datasets.  I may eventually submit these changes to `tensorflow/models`.  `azavea/models` seems to be a snapshot of upstream, but if these changes are more appropriate for that repo then I can submit them there.

### Checklist

- [x] Ran scripts/format_code and commited any changes
- [x] Documentation updated if needed
- [x] PR has a name that won't get you publicly shamed for vagueness

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as rebuilding the Docker image.
* Include test case, and expected output if not captured by automated tests.

### CODE REVIEW

**Comment by lewfish** [comment]
I think it's best to put these changes in https://github.com/azavea/models since you may want to make other changes down the road and it will be a little awkward having a sequence of patches in the `install_deps` script.

**Comment by jamesmcclain** [comment]
Can we bring `azavea/models` up to upstream?

**Comment by lewfish** [comment]
> Can we bring azavea/models up to upstream?

We could try. It might break things but hopefully not.

**Comment by jamesmcclain** [comment]
This will not be merged in its present form, but I would like to wait to see what happens with https://github.com/tensorflow/models/pull/5102 before proceeding.

**Comment by jamesmcclain** [comment]
Closed in favor of https://github.com/azavea/models/pull/1

**Pull request closed without merging**
