### PR TITLE
Make Subsequent Docker Images Related

### PR DESCRIPTION
**Pull request by jamesmcclain**
## Overview

Cause subsequent docker images to be more closely related (saves about 5 GB per image and causes faster builds and downloads).

- [x] Updated `docs/changelog.rst`
- [x] Added `needs-backport` label if PR is bug fix that applies to previous minor release
- [x] Ran scripts/format_code and committed any changes
- [x] Documentation updated if needed
- [x] PR has a name that won't get you publicly shamed for vagueness

### CODE REVIEW

**Comment by lewfish** [comment]
I'm not sure I understand the intention behind this PR. The steps of the Dockerfile that copy the RV source code happen at the end of the Dockerfile, so all of the time-consuming and storage intensive steps should already be cached and copied when the image is re-built.

**Comment by jamesmcclain** [comment]
> I'm not sure I understand the intention behind this PR. The steps of the Dockerfile that copy the RV source code happen at the end of the Dockerfile, so all of the time-consuming and storage intensive steps should already be cached and copied when the image is re-built.

Subsequent raster-vision images on quay are mostly unrelated and differ by about 4 GB or so.

My specific use case for wanting incremental differences to be smaller (besides aesthetic and storage-related) is that I frequently develop raster-vision patches in the context of projects which I then turn into raster-vision pull requests.  As those patches are merged, I update the build for the project.

**Comment by jamesmcclain** [comment]
It should also speed the CI up, too.

**Comment by lewfish** [comment]
This seems useful. Right now I'm testing an alternative approach which would be simpler, but I don't know if it will work.

**Pull request closed without merging**
